[tool.poetry]
name = "bridge"
version = "0.1.0"
description = ""
authors = ["Abin Simon <mail@meain.io>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "2.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
