# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(through='core.TaughtBy', to='core.Subject', verbose_name='Subjects'),
        ),
    ]
