# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_class_subjects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
    ]
