# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170301_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
