# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170301_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Event title')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('event_description', models.TextField(verbose_name='Description')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Class', verbose_name='Assigned to')),
            ],
        ),
    ]
