# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170329_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
