# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_register_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_no',
        ),
    ]
