# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='CS 6A', max_length=10),
            preserve_default=False,
        ),
    ]
