# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20170329_1936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Class",
                verbose_name="Assigned to",
            ),
        ),
    ]
