# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170329_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.TextField(null=True),
        ),
    ]
