# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20170430_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="data",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="date",
            field=models.CharField(max_length=12, null=True, verbose_name="date"),
        ),
    ]
