# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20170430_0830"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="period",
            field=models.SmallIntegerField(
                max_length=1, null=True, verbose_name="Period"
            ),
        ),
    ]
